source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'LIHImageSlider_Example', :exclusive => true do
  pod 'LIHImageSlider', :path => '../'
end

target 'LIHImageSlider_Tests', :exclusive => true do
  pod 'LIHImageSlider', :path => '../'

  
end
